### ISSUE TITLE
Sqlite par défaut

### ISSUE THREAD

**Issue by teymour** [24eme/monactivite#1]
Afin de faciliter la découverte du logiciel, il serait plus intéressant que par défaut, il soit configuré pour fonctionner avec sqlite.

Il faudrait donc :
 - ajouter la dépendance dans composer
 - preconfigurer le parameter.yml et config.yml pour sqlite au lieu de mysql

**Comment by wincelau** [comment]
sqlite est désormais configuré par défaut : e318af4a50d9aa5c192cc910fed5b9d7faa16391

Il reste à ajouter la dépendance dans composer.
