### ISSUE TITLE
Confirmation d'ajout de source

### ISSUE THREAD

**Issue by teymour** [24eme/monactivite#2]
Lorsqu'on a ajouté une source, il est assez troublant de tomber sur une page "crud" qui propose que sa suppression. Retourner sur la page d'ajout de source avec un flash indiquant que la source a été ajoutée serait plus rassurant

**Comment by wincelau** [comment]
C'est fait la création d'une source retourne désormais sur la liste des sources avec un message flash informatif : b2b4e95df2fa7ad3025f63684664f721d1b4c59b
