### ISSUE TITLE
Format tablette

### ISSUE THREAD

**Issue by teymour** [24eme/monactivite#4]
en format tablette, le détail des activités (sujet des mails, détails des commits, non de l'event) n'apparait pas.

**Comment by teymour** [comment]
La majorité des pages ne sont pas très fonctionnelle au format tablette (petits écrans)

**Comment by teymour** [comment]
Autre exemple :  #3 (fermé car doublons)

**Comment by wincelau** [comment]
J'ai adapté les pages à la taille "medium" de boostrap de 992px à 1200px : 283f7ca3716af3118faa6aa8d920ecb5edd7828a
