### ISSUE TITLE
gestion des évènements sur plusieurs (ical)

### ISSUE THREAD

**Issue by teymour** [24eme/monactivite#5]
Quand l'ical propose un évènement sur plusieurs jours, seul le premier est intégré dans monactivité.

Un exemple : 

> BEGIN:VCALENDAR
> VERSION:2.0
> PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
> BEGIN:VEVENT
> CREATED:20170207T201532Z
> LAST-MODIFIED:20170207T201634Z
> DTSTAMP:20170207T201634Z
> UID:6464d52d-3727-489f-a513-e21076f40802
> SUMMARY:fine tunning projet XXX
> DTSTART;VALUE=DATE:20170219
> DTEND;VALUE=DATE:20170223
> TRANSP:TRANSPARENT
> END:VEVENT
> END:VCALENDAR

**Comment by wincelau** [comment]
C'est corrigé et géré dans les tests unitaires : a4ac3c7a74e41ac13869e047b33285f1f32aa10a
