### ISSUE TITLE
[Mail] Gestion des destinataires en cc 

### ISSUE THREAD

**Issue by teymour** [24eme/monactivite#6]
Ca serait vraiment bien de pouvoir créer des filtres pour les destinataire en copie, comme dans les mailleurs où on peut faire des filtres "To ou Cc".

Une solution serait de mettre les headers des destinataires dans le contenu des messages et de pouvoir créer un filtre sur le contenu des messages.

**Comment by wincelau** [comment]
C'est fait : e036e093eefa3dc25fac798a68c214c2c1299bb3
