### ISSUE TITLE
[git] ajouter une source qui ne suit les commits associés que d'une unique branche

### ISSUE THREAD

**Issue by teymour** [24eme/monactivite#7]
Afin de mieux taguer les commits d'un projet, ça serait bien de pouvoir suivre que les commits d'une branche plutot que d'avoir tous les commits du dépot.

**Comment by wincelau** [comment]
C'est en place : a7e6bfa28e2fb6bcac77efb2251a0ea74fee2cae, avec également la branche mise en attribut
