### ISSUE TITLE
Problème d'encodage

### ISSUE THREAD

**Issue by teymour** [24eme/monactivite#8]
Le mail suivant : [reunion_fin_de_sprint3](https://github.com/24eme/monactivite/files/5457985/reunion_fin_de_sprint3.txt) est intégré avec des problèmes d'encodage dans monactivité : 

« Bonjour ? toutes, bonjour ? tous, Les annonces d'hier nous laissent penser qu'il sera peut ?tre difficile de nous voir »

**Comment by wincelau** [comment]
Merci c'est corrigé mb_convert_encoding ne gérait pas l'encodage windows-1256 je suis donc passé par iconv 128e1efa6dccb6801f8015497191f35df470bb38
